spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=fastTrade;encrypt=true;trustServerCertificate=true;
    username: sa
    password: "@Andrehermoza1"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect


